name: Tests

on: [push, pull_request]

jobs:
  test:
    name: >-
      libev_scheduler ${{matrix.os}}, ${{matrix.ruby}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        ruby: [ '3.0' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
      - name: Install dependencies
        run: bundle install
      - name: Compile C-extension
        run: bundle exec rake compile
      - name: Run tests
        run:  bundle exec rake test
